### ISSUE TITLE
UKI: upgrade fails

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2203]
**Kairos version:**

**CPU architecture, OS, and Version:**

**Describe the bug**

Upgrade with UKI seems to fail with:

```
Reading udevdata of device: /run/udev/data/b252:0
252:3

Reading udevdata of device: /run/udev/data/b252:0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd292e5]

goroutine 1 [running]:
github.com/kairos-io/kairos-agent/v2/pkg/config.setUpgradeSourceSize(0x57c2f20?, 0x60cb080?)
        /go/src/github.com/kairos-io/kairos-agent/pkg/config/spec.go:344 +0x25
github.com/kairos-io/kairos-agent/v2/pkg/config.NewUpgradeSpec(0xc000002000)
        /go/src/github.com/kairos-io/kairos-agent/pkg/config/spec.go:323 +0xa6a
github.com/kairos-io/kairos-agent/v2/pkg/config.ReadSpecFromCloudConfig(0xc000002000, {0x11244e2, 0x7})
        /go/src/github.com/kairos-io/kairos-agent/pkg/config/spec.go:755 +0xcc
github.com/kairos-io/kairos-agent/v2/pkg/config.ReadUpgradeSpecFromConfig(0x0?)
        /go/src/github.com/kairos-io/kairos-agent/pkg/config/spec.go:738 +0x1f
github.com/kairos-io/kairos-agent/v2/internal/agent.generateUpgradeSpec({0xc000353950?, 0xc0000061a0?}, 0x0?, 0x0, {0x6061e20, 0x3, 0x3}, 0x5a?, 0x3e?)
        /go/src/github.com/kairos-io/kairos-agent/internal/agent/upgrade.go:196 +0x1ef
github.com/kairos-io/kairos-agent/v2/internal/agent.upgrade({0xc000353950?, 0xc000415c00?}, 0x0?, 0x5e?, {0x6061e20?, 0xe4bcf7?, 0x1127525?}, 0x25?, 0x75?)
        /go/src/github.com/kairos-io/kairos-agent/internal/agent/upgrade.go:79 +0x32
github.com/kairos-io/kairos-agent/v2/internal/agent.Upgrade({0xc000353950, 0x29}, 0x8?, 0x0?, {0x6061e20, 0x3, 0x3}, 0x1?, 0x0?)
        /go/src/github.com/kairos-io/kairos-agent/internal/agent/upgrade.go:74 +0xd5
main.glob..func3(0xc000415e00)
        /go/src/github.com/kairos-io/kairos-agent/main.go:181 +0x31c
github.com/urfave/cli/v2.(*Command).Run(0x606bda0, 0xc000415e00, {0xc0004176b0, 0x3, 0x3})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.26.0/command.go:277 +0x9d8
github.com/urfave/cli/v2.(*Command).Run(0xc0000da9a0, 0xc000415c40, {0xc000034080, 0x4, 0x4})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.26.0/command.go:270 +0xc25
github.com/urfave/cli/v2.(*App).RunContext(0xc0000cc5a0, {0x57bbb80?, 0x60cb080}, {0xc000034080, 0x4, 0x4})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.26.0/app.go:335 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
```

**To Reproduce**

Build an UKI iso with: https://deploy-preview-133--kairos-io.netlify.app/docs/installation/trustedboot/#building-installable-medium, install the system.

Then try to follow https://deploy-preview-133--kairos-io.netlify.app/docs/upgrade/trustedboot/#example-e2e-image-generation and generate an upgrade image. Use the image with an UKI system to do the upgrade. 

**Expected behavior**

To not panic.

It looks  `.Source` is nil in https://github.com/kairos-io/kairos-agent/blob/1a46f0910ffa10fd12c791e9d91c5a4ba7fda008/pkg/config/spec.go#L344 .

**Logs**

**Additional context**

**Comment by jimmykarily** [comment]
@Itxaka can you please link to the fix before we close this?

**Comment by Itxaka** [comment]
https://github.com/kairos-io/kairos-agent/pull/219
