### ISSUE TITLE
:bug: Merging a null value into something results in a null pointer exception

### ISSUE THREAD

**Issue by Akvanvig** [kairos-io/kairos#2735]
**Kairos version:**

PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
KAIROS_MODEL="generic"
KAIROS_SOFTWARE_VERSION_PREFIX="k3s"
KAIROS_ID="kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/ubuntu:24.04-core-amd64-generic-v3.1.0"
KAIROS_ARTIFACT="kairos-ubuntu-24.04-core-amd64-generic-v3.1.0"
KAIROS_FLAVOR_RELEASE="24.04"
KAIROS_FAMILY="ubuntu"
KAIROS_VARIANT="core"
KAIROS_IMAGE_LABEL="24.04-core-amd64-generic-v3.1.0"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_ID_LIKE="kairos-core-ubuntu-24.04"
KAIROS_VERSION_ID="v3.1.0"
KAIROS_FLAVOR="ubuntu"
KAIROS_RELEASE="v3.1.0"
KAIROS_REGISTRY_AND_ORG="quay.io/kairos"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_NAME="kairos-core-ubuntu-24.04"
KAIROS_VERSION="v3.1.0"
KAIROS_PRETTY_NAME="kairos-core-ubuntu-24.04 v3.1.0"
KAIROS_TARGETARCH="amd64"

**CPU architecture, OS, and Version:**

Linux kairos-test 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**

When a key with a null value is merged into an existing key, it returns a null pointer error. 

**To Reproduce**

```
# printf "#cloud-config\nkey:\n - \"valA\"\n" > /usr/local/cloud-config/test1.yaml
# printf "#cloud-config\nkey: \n" > /usr/local/cloud-config/test2.yaml
# kairos-agent config get key
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0xdaea20]
...
```

**Expected behavior**

Two different options here:
1. null out the current value (eg. string -> "", arrays -> [] and maps to {}) 
2. it could just ignore the new null value

**Logs**

```
# kairos-agent config get key
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0xdaea20]

goroutine 1 [running]:
github.com/kairos-io/kairos-sdk/collector.DeepMerge({0x10ac940, 0xc000238930}, {0x0, 0x0})
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.2.3/collector/collector.go:182 +0xe0
github.com/kairos-io/kairos-sdk/collector.deepMergeMaps(0xc0004a6030, 0xc000018e60?)
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.2.3/collector/collector.go:158 +0x117
github.com/kairos-io/kairos-sdk/collector.DeepMerge({0x111d680, 0xc0004a6030}, {0x111d680, 0xc0004a7830})
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.2.3/collector/collector.go:191 +0x1fe
github.com/kairos-io/kairos-sdk/collector.(*Config).MergeConfig(0xc00006da70, 0xc00006da18)
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.2.3/collector/collector.go:102 +0x55
github.com/kairos-io/kairos-sdk/collector.Configs.Merge({0xc000221d00, 0x10, 0x0?})
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.2.3/collector/collector.go:216 +0xa5
github.com/kairos-io/kairos-sdk/collector.Scan(0xc00008be00, 0x4a911d8)
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.2.3/collector/collector.go:238 +0x269
github.com/kairos-io/kairos-agent/v2/pkg/config.scan(0xc00010c3c0, {0xc00051f6c0, 0x3, 0x0?})
        /go/src/github.com/kairos-io/kairos-agent/pkg/config/config.go:362 +0xe5
github.com/kairos-io/kairos-agent/v2/pkg/config.ScanNoLogs({0xc00051f6c0, 0x3, 0x3})
        /go/src/github.com/kairos-io/kairos-agent/pkg/config/config.go:345 +0x129
main.init.func12(0xc000246380)
        /go/src/github.com/kairos-io/kairos-agent/main.go:359 +0x15e
github.com/urfave/cli/v2.(*Command).Run(0x5578f80, 0xc000246380, {0xc00046fbe0, 0x2, 0x2})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/command.go:276 +0x97d
github.com/urfave/cli/v2.(*Command).Run(0x5578cc0, 0xc0002462c0, {0xc00024a420, 0x3, 0x3})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/command.go:269 +0xbb7
github.com/urfave/cli/v2.(*Command).Run(0xc0000faf20, 0xc000246100, {0xc00003e080, 0x4, 0x4})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/command.go:269 +0xbb7
github.com/urfave/cli/v2.(*App).RunContext(0xc000401600, {0x4beea70, 0x5609c40}, {0xc00003e080, 0x4, 0x4})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:333 +0x58b
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:307
main.main()
        /go/src/github.com/kairos-io/kairos-agent/main.go:832 +0x3c8
```

**Additional context**

Would be nice having a way of overriding exiting objects like lists instead of just appending to them, so created a pull-request with a possible implementation of the first case of expected behavior. Shouldn't affect any existing configs since this has previously just caused an error

**Comment by mauromorales** [comment]
@Akvanvig thanks for reporting and providing a fix 🙇
