### ISSUE TITLE
Running Auroraboot with no params gives a kernel panic

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#3024]
```
$ go run main.go                                      
2024-11-19T10:30:44+01:00 INF Downloading https://github.com//releases/download//core--.iso...
2024-11-19T10:30:44+01:00 INF Downloading https://github.com//releases/download//core--.squashfs...
2024-11-19T10:30:44+01:00 INF Downloading https://github.com//releases/download//core---initrd...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe8601f]

goroutine 31 [running]:
github.com/kairos-io/AuroraBoot/pkg/ops.download({0x14fd000, 0x1e34fc0}, {0xc0004b7a00, 0x36}, {0xc0004993c0, 0x1c})
	/home/itxaka/projects/AuroraBoot/pkg/ops/network.go:57 +0x21f
github.com/kairos-io/AuroraBoot/deployer.(*Deployer).StepDownloadSquashFS.DownloadArtifact.func4({0x14fd000?, 0x1e34fc0?})
	/home/itxaka/projects/AuroraBoot/pkg/ops/network.go:42 +0x2d
github.com/spectrocloud-labs/herd.(*Graph).Run.func3({0x14fd000?, 0x1e34fc0?}, 0xc0005d1470, {0x117acdd, 0x11}, 0x0?)
	/home/itxaka/go/pkg/mod/github.com/spectrocloud-labs/herd@v0.4.2/dag.go:159 +0x43
created by github.com/spectrocloud-labs/herd.(*Graph).Run in goroutine 1
	/home/itxaka/go/pkg/mod/github.com/spectrocloud-labs/herd@v0.4.2/dag.go:158 +0x633
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe8601f]

goroutine 29 [running]:
github.com/kairos-io/AuroraBoot/pkg/ops.download({0x14fd000, 0x1e34fc0}, {0xc0004b7980, 0x34}, {0xc000499380, 0x1a})
	/home/itxaka/projects/AuroraBoot/pkg/ops/network.go:57 +0x21f
github.com/kairos-io/AuroraBoot/deployer.(*Deployer).StepDownloadInitrd.DownloadArtifact.func3({0x14fd000?, 0x1e34fc0?})
	/home/itxaka/projects/AuroraBoot/pkg/ops/network.go:42 +0x2d
github.com/spectrocloud-labs/herd.(*Graph).Run.func3({0x14fd000?, 0x1e34fc0?}, 0xc0005d1470, {0x1177e54, 0xf}, 0x0?)
	/home/itxaka/go/pkg/mod/github.com/spectrocloud-labs/herd@v0.4.2/dag.go:159 +0x43
created by github.com/spectrocloud-labs/herd.(*Graph).Run in goroutine 1
	/home/itxaka/go/pkg/mod/github.com/spectrocloud-labs/herd@v0.4.2/dag.go:158 +0x633
exit status 2
```

There should be a safety check that if we are not passing a release, an iso, or a container, we dont start aurora and exit gracefully. Instead this is trying to download the release isos with no versions and panicking

**Comment by jimmykarily** [comment]
Eventually, we should move the "declarative" root command of Auroraboot to a subcommand but for now let's just handle this properly with an error message.
