### ISSUE TITLE
:bug: Stacktrace and blocked when there are no networks on a machine

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#703]
**Kairos version:**

Kairos 1.4.0 with K3S (provider-kairos release)

**CPU architecture, OS, and Version:**

amd64

**Describe the bug**

When booting an image, if the machine doesn't have any network a panic error is shown, and it is not possible to quit it.

**To Reproduce**

Boot a machine with Kairos and no network connections

**Expected behavior**

It should tell the user about the issues without showing an error stacktrace, and it should not block the user from accessing the terminal.

**Logs**

![IMG_1978](https://user-images.githubusercontent.com/433958/214001861-d9a2dcfc-84b5-412d-b4b2-d8964b721fec.jpg)

```
Provider kairos at /system/providers/agent-provider-kairos had an error: error while executing plugin: exit status 22022/10/11 15:51:55 [zeroconf] no suitable IPv4 interf ace: udp4: failed to join any of these interfaces: [I
2022/10/11 15:51:55 (zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: [I panic:
goroutine 1 [running):
github.com/pterm/pterm. checkFata!(...)
/go/pkg/mod/github.com/perm/pterm@vo.12.50/prefix_printer.go:348
github.com/pterm/pterm. (*PrefixPrinter).PrintIn(ox23a5c60, foxco008df558, 0×1, 0x13) /go/pkg/mod/github.com/pterm/pterm@vo.12.50/prefix_printer.go:265+0X191
github.com/mudler/edgevon/pkg/lpgger.Logger.Fatal ((0×27?3, (Oxc000b968a0?, 0x1?, 0X1993012}) /go/pkg/mod/github.com/mudler/edgevpn@v0.15.3/pkg/logger/logger.go:81+Oxf7
github.com/mudler/edgevpn/pkg/node. (*Node) .startNetwork (OXc0000f 1200, {0X1987f08?, OXC000042050})
/go/pkg/mod/github.com/mudler/edgevpn@vo.15.3/pkg/node/node.go:185+Oxaef
github.com/mudler/edgevpn/pkg/node. (*Node) .Start (OxC0000f 1200, (0x1987f08, 0×c000042050}) /go/pkg/mod/github.com/muciler/edgevpn@vo.15.3/pkg/node/node.go:124+0×195
github.com/mudler/go-nodepair-Receive ({0×1987f08, 0xc0000420501, [0x11aac20, 0X.0000a28483, (0xco008dfc30, 0x1, 0x13) /go/pkg/mod/github.com/mudler/go-nodepair@vo.0.0-20220507212557-7d47aa3cc1f1/pairing.go:148+0XC5
github.com/kairos-jo/provider-kairos/internal/provider. Install (Oxc000a77aa0)
/build/internal/provider/insta11.go:22 +0×151
github.com/mudler/go-pluggable.PluginFactory.Run (0X12ac540?, (Ox7ffdldbeceff, oxd],(0x197c1a0, Oxc00000e010], (0x197c10, 0XC00000e0181)
/go/pkg/mod/github.com/mudler/go-pluggable@vo.0.0-20220716112424-109d463e3ff3/factory.go:73+0x1eb
github.com/kairos-io/provider-kairos/internal/provider.Start ()
/build/internal/provider/start.go:32 +0×28d main.main()
/build/main.go:23 +0×51
```

**Additional context**

**Comment by mauromorales** [comment]
The issue was likely caused by the non-free drivers in the mac, no need to focus on this atm
